services:
  react-app:
    build: .
    container_name: react-container
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - sonarqube
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30sec
      timeout: 10sec
      retries: 3

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    depends_on:
      - db
